//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelicula
    {
        public int idpelicula { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string actores { get; set; }
        public string director { get; set; }
        public int costoalquiler { get; set; }
        public int cantidad { get; set; }
    }
}
